site_name: My Blogs
site_url: https://definieren.github.io/template
site_author: definieren
strict: false

theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/brightness-7
        name: 切换至夜间模式
    - scheme: slate
      primary: black
      accent: white
      toggle: 
        icon: material/brightness-4
        name: 切换至白天模式
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.expand
    - search.share
  language: zh
  icon:
    repo: fontawesome/brands/github
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

edit_uri: edit/main/docs
repo_url: https://github.com/definieren/definieren.github.io/template
repo_name: template

copyright: Copyright &copy; 2023 definieren

hooks:
  - hooks/on_env.py

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/definieren
    - icon: fontawesome/solid/paper-plane
      link: mailto:<1343004263@qq.com>

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - 'static/js/math-csr.js?math-csr'
  - 'assets/vendor/mathjax/es5/tex-mml-chtml.js?math-csr'

extra_css:
  - 'static/css/extra.css?v=14'

nav: 
  - Home: index.md
  - 缺省源: DefaultSource/DefaultSource.md
  - 数学:
    - 组合数学:
      - 组合数预处理: Math/Combinatorics/Combination.md
      - 静态取模类: Math/Combinatorics/StaticModint.md
      - 动态取模类: Math/Combinatorics/DynamicModint.md
      - 快速取模: Math/Combinatorics/FastMod.md
    - 多项式:
      - 多项式: Math/Polynomial/Poly.md
      - 拉格朗日插值: Math/Polynomial/Interpolation.md
      - 集合幂级数: Math/Polynomial/SetPowerSeries.md
    - 数论:
      - 质因数分解: Math/NumberTheory/Factorize.md
      - 线性筛: Math/NumberTheory/Sieve.md
      - 原根: Math/NumberTheory/PrimitiveRoot.md
    - 线性代数:
      - 行列式: Math/LinearAlgebra/Determinant.md
      - Pfaffian: Math/LinearAlgebra/Pfaffian.md
      - 特征多项式: Math/LinearAlgebra/CharacteristicPolynomial.md
  - 字符串:
  - 图论:
    - 网络流: Graph/Flow.md
    - 图: Graph/GraphBase.md
    - 双极定向: Graph/st-Numbering.md
  - 数据结构:
    - 线段树: DataStructure/SegmentTree.md
    - RMQ: DataStructure/RMQ.md
    - Bitset: DataStructure/Bitset.md
    - 哈希表: DataStructure/HashMap.md
    - 并查集: DataStructure/DisjointSet.md
    - 可删堆: DataStructure/Heap.md
  - 其他:
    - 凸相关:
      - SMAWK: Other/Convex/SMAWK.md
    - 高精度: Other/BigNum.md
    - 有理数类: Other/Rational.md
    - YesNo: Other/YesNo.md
